#!/bin/bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Abre mi diario actual con NeoVim
##?
##? Usage:
##?    open
docs::parse "$@"

YEAR=$(date +"%Y")

nvim $TECH_DIARY/developers/mruiz/$YEAR.md +
