#!/bin/bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Actualiza el diario y abre mi diario actual con NeoVim
##?
##? Usage:
##?    open
docs::parse "$@"

cd $TECH_DIARY
YEAR=$(date +"%Y")

git pull

nvim $TECH_DIARY/developers/mruiz/$YEAR.md +
