#!/bin/bash

##################################################################
#
# Script para subir el commit del developers diary
#
##################################################################

NOW=$(date +"%d/%m/%Y")

# exit when any command fails
set -e

cd $TECH_DIARY

git commit -a -m "mruiz $NOW"
git pull --rebase
git push
