#!/bin/bash

##################################################################
#
# Limpia los temporales del universo gestiona
# 
##################################################################

rm -rf /home/mruiz/__tmp/gestiona-tests/*

