#!/bin/bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Lista de los projectos disponibles en local
##?
##? Usage:
##?    projects [<name_project>]
docs::parse "$@"

source $DOTFILES_PATH/shell/functions.sh

function ask_action () {

	# Options 
	a_code=" Code" 
	a_redmine=" Redmine" 
	a_history=" History" 

	action=$(echo -e "$a_code\n$a_redmine\n$a_history" | fzf)
}

# echo "Name project recibed: $name_project."
if [ -z "$name_project" ] ; then
	# sacamos el selector de proyectos
	# project=$(ls "$TECH_PROJECTS" | fzf --preview='tech::projects::showInfo {}')
	project=$(ls "$TECH_PROJECTS" | fzf --preview='cat $TECH_PROJECTS/{}')
else
	# se ha indicado proyecto
	project=$name_project
fi

echo "Selected project: $project."
tech::projects::showInfo $project 

# declare -A projectData
# projectData=( 
# 	["name"]="$name"
# 	["redmine"]="$redmine"
# 	["repo"]="$repo"
# )

ask_action $project

case "$action" in 

	$a_code)
		if [[ "false" = "$dotnet" ]] ; then

			if [[ "false" = "$isWorkspace" ]] ; then
				echo "Open project with IDE IntelliJ" 
				intellij $TECH_PROJECTS_CODE/$project &>/dev/null & 
			else
				echo "Open workspace with IDE IntelliJ" 
				intellij $TECH_WORKSPACE/$project &>/dev/null & 
			fi

		fi
		if [[ "true" = "$dotnet" ]] ; then
			echo "Open project with IDE Rider" 
			# es un proyecto de NET, abrimos con el Rider
			rider $TECH_PROJECTS_CODE/$project &>/dev/null & 
		fi

		echo "IDE abierto"

		;;
		
	$a_redmine)
		echo "open redmine $redmine"
		qutebrowser --target window $redmine
		;;

	$a_history)
		echo "open webs app $repo"
		qutebrowser --target window $repo
		;;

	*)
		echo "errooooooorrr"
		exit 1
		;;

esac

